version: "3.9"
services:
  traefik:
    image: traefik:2.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    command:
      - --providers.docker
      - --providers.docker.swarmmode
      - --providers.docker.exposedbydefault=false
      - --entryPoints.open.address=:80
      - --entryPoints.secure.address=:443
      # Force http to https redirect
      - --entrypoints.open.http.redirections.entryPoint.to=secure
      - --entrypoints.open.http.redirections.entryPoint.scheme=https
      - --accesslog
      - --api
      - --log
      - --log.level=DEBUG
    deploy:
      labels:
        # Make Traefik dashboard available via Traefik.
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.tls=true
        - traefik.http.services.traefik.loadbalancer.server.port=8080
  apache:
    # This is the same compose image but pushed to ghcr.
    image: ghcr.io/tuupola/apache-php-example
    # Uncomment this if you want to dev with swarm.
    # volumes:
    #   - ./:/srv/www
    deploy:
      replicas: 3
      # Do not create Docker virtual IP endpoint since Traefik is used
      # for load balancing.
      endpoint_mode: dnsrr
      labels:
        # Make Apache available via Traefik.
        - traefik.enable=true
        - traefik.http.routers.apache.rule=Host(`example.localhost`)
        - traefik.http.routers.apache.tls=true
        - traefik.http.services.apache.loadbalancer.server.port=80
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./docker/mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql