services:
  traefik:
    image: traefik:2.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true
      - --accesslog
      - --log
  apache:
    build:
      context: ./docker/apache
    volumes:
      - ./:/srv/www
    labels:
      - traefik.enable=true
      - traefik.http.routers.slim.rule=Host(`slim.localhost`)
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./docker/mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql