version: "3.9"
services:
  caddy:
    image: ghcr.io/tuupola/caddy-proxy-example
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./:/srv/www
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Make sure Caddy uses the correct network for service discovery.
      # https://github.com/lucaslorentz/caddy-docker-proxy/issues/207
      - CADDY_INGRESS_NETWORKS=slim_default
  fpm:
    image: ghcr.io/tuupola/php-fpm-example
    # Uncomment this if you want to dev with swarm.
    # volumes:
    #   - ./:/srv/www
    deploy:
      replicas: 3
      # Do not create Docker virtual IP endpoint since Caddy is used
      # for load balancing.
      endpoint_mode: dnsrr
      labels:
        caddy: example.localhost
        caddy.root: "* /srv/www/public"
        caddy.file_server:
        caddy.php_fastcgi: "{{upstreams 9000}}"
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./docker/mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql