version: "3"
services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/srv/www
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
  fpm:
    build:
      context: ./fpm
    volumes:
      - ../:/srv/www
