version: "3"
services:
  nginx:
    image: slim-nginx
    build:
      context: ./nginx
    volumes:
      - ../:/srv/www
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
  fpm:
    image: slim-fpm
    build:
      context: ./fpm
    volumes:
      - ../:/srv/www
  mariadb:
    image: slim-mariadb
    build:
      context: ./mariadb
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql
