apiVersion: apps/v1
kind: Deployment
metadata:
  name: slim
spec:
  selector:
    matchLabels:
      app: slim
  replicas: 3
  template:
    metadata:
      labels:
        app: slim
    spec:
      containers:
        - name: slim
          image: ghcr.io/tuupola/apache-php-example:latest
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slim-ingress
spec:
  #ingressClassName: slim
  rules:
  - host: "example.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: slim
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: slim
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: slim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: secret
          volumeMounts:
            - name: database-seed
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: database-seed
          configMap:
            name: database-seed
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mariadb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-seed
data:
  data.sql: |-
    DROP TABLE IF EXISTS cars;

    CREATE TABLE cars (
        brand CHAR(32) DEFAULT NULL
    );

    LOCK TABLES cars WRITE;
    INSERT INTO cars VALUES ("Tesla");
    INSERT INTO cars VALUES ("Audi");
    INSERT INTO cars VALUES ("BMW");
    UNLOCK TABLES;
