version: "3"
services:
  apache:
    image: slim-docker-apache
    volumes:
      - ./:/srv/www
    ports:
      - 80:80
    deploy:
      replicas: 3
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./docker/mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql
