services:
  caddy:
    image: caddy:2.6
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    command: caddy reverse-proxy --from example.localhost --to apache
  apache:
    image: ghcr.io/tuupola/apache-php-example
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    volumes:
      # Use a bind mount for easy development.
      - ./:/srv/www
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./docker/mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql